package handlers

const (
	callbackMainMenuRegistration     = "nav:registration:start"
	callbackMainMenuHelp             = "nav:main:help"
	callbackMainMenuNeedHelp         = "nav:main:need_help"
	callbackMainMenuProfile          = "nav:main:profile"
	callbackMainMenuAbout            = "nav:main:about"
	callbackProfileHistory           = "profile:history"
	callbackProfileEdit              = "profile:edit"
	callbackProfileSecurity          = "profile:security"
	callbackProfileBack              = "profile:back"
	callbackProfileCoins             = "profile:coins"
	callbackCoinsHowToGet            = "profile:coins:get"
	callbackCoinsHowToSpend          = "profile:coins:spend"
	callbackCoinsLevels              = "profile:coins:levels"
	callbackAboutHowItWorks          = "about:how"
	callbackAboutRules               = "about:rules"
	callbackAboutInitiator           = "about:initiator"
	callbackAboutSupport             = "about:support"
	callbackAboutBack                = "about:back"
	callbackRegistrationAgeUnder18   = "registration:age:under18"
	callbackRegistrationAge18_24     = "registration:age:18_24"
	callbackRegistrationAge25_34     = "registration:age:25_34"
	callbackRegistrationAge35_44     = "registration:age:35_44"
	callbackRegistrationAge45_54     = "registration:age:45_54"
	callbackRegistrationAge55_64     = "registration:age:55_64"
	callbackRegistrationAge65Plus    = "registration:age:65_plus"
	callbackRegistrationSexMale      = "registration:sex:male"
	callbackRegistrationSexFemale    = "registration:sex:female"
	callbackRegistrationSkipLocation = "registration:location:skip"
	callbackRegistrationAboutToggle  = "registration:about:toggle"
	callbackRegistrationAboutConfirm = "registration:about:confirm"
)
